use std::collections::HashSet;
use std::fmt::Write;
use std::fs;
use std::path::Path;

// (name, svg-id, value-type)
const ATTRIBUTES: &[(&str, &str, &str)] = &[
    ("AccentHeight", "accent-height", "String"),
    ("Accumulate", "accumulate", "String"),
    ("Actuate", "actuate", "String"),
    ("Additive", "additive", "String"),
    ("AlignmentBaseline", "alignment-baseline", "String"),
    ("Alphabetic", "alphabetic", "String"),
    ("Amplitude", "amplitude", "String"),
    ("ArabicForm", "arabic-form", "String"),
    ("Arcrole", "arcrole", "String"),
    ("Ascent", "ascent", "String"),
    ("AttributeName", "attributeName", "String"),
    ("AttributeType", "attributeType", "String"),
    ("Azimuth", "azimuth", "String"),
    ("Base", "base", "String"),
    ("BaseFrequency", "baseFrequency", "String"),
    ("BaselineShift", "baseline-shift", "String"),
    ("BaseProfile", "baseProfile", "String"),
    ("Bbox", "bbox", "String"),
    ("Begin", "begin", "String"),
    ("Bias", "bias", "String"),
    ("By", "by", "String"),
    ("CalcMode", "calcMode", "String"),
    ("CapHeight", "cap-height", "String"),
    ("Class", "class", "String"),
    ("Clip", "clip", "String"),
    ("ClipPath", "clip-path", "String"),
    ("ClipRule", "clip-rule", "String"),
    ("ClipPathUnits", "clipPathUnits", "String"),
    ("Color", "color", "Color"),
    ("ColorInterpolation", "color-interpolation", "String"),
    (
        "ColorInterpolationFilters",
        "color-interpolation-filters",
        "String",
    ),
    ("ColorProfile", "color-profile", "String"),
    ("ColorRendering", "color-rendering", "String"),
    ("ContentScriptType", "contentScriptType", "String"),
    ("ContentStyleType", "contentStyleType", "String"),
    ("Cursor", "cursor", "String"),
    ("Cx", "cx", "Length"),
    ("Cy", "cy", "Length"),
    ("D", "d", "String"),
    ("Descent", "descent", "String"),
    ("DiffuseConstant", "diffuseConstant", "String"),
    ("Direction", "direction", "String"),
    ("Display", "display", "String"),
    ("Divisor", "divisor", "String"),
    ("DominantBaseline", "dominant-baseline", "String"),
    ("Dur", "dur", "String"),
    ("Dx", "dx", "String"),
    ("Dy", "dy", "String"),
    ("EdgeMode", "edgeMode", "String"),
    ("Elevation", "elevation", "String"),
    ("EnableBackground", "enable-background", "String"),
    ("End", "end", "String"),
    ("Exponent", "exponent", "String"),
    (
        "ExternalResourcesRequired",
        "externalResourcesRequired",
        "String",
    ),
    ("Fill", "fill", "String"),
    ("FillOpacity", "fill-opacity", "String"),
    ("FillRule", "fill-rule", "String"),
    ("Filter", "filter", "String"),
    ("FilterRes", "filterRes", "String"),
    ("FilterUnits", "filterUnits", "String"),
    ("FloodColor", "flood-color", "String"),
    ("FloodOpacity", "flood-opacity", "String"),
    ("Font", "font", "String"),
    ("FontFamily", "font-family", "String"),
    ("FontSize", "font-size", "String"),
    ("FontSizeAdjust", "font-size-adjust", "String"),
    ("FontStretch", "font-stretch", "String"),
    ("FontStyle", "font-style", "String"),
    ("FontVariant", "font-variant", "String"),
    ("FontWeight", "font-weight", "String"),
    ("Format", "format", "String"),
    ("From", "from", "String"),
    ("Fx", "fx", "String"),
    ("Fy", "fy", "String"),
    ("G1", "g1", "String"),
    ("G2", "g2", "String"),
    ("GlyphName", "glyph-name", "String"),
    (
        "GlyphOrientationHorizontal",
        "glyph-orientation-horizontal",
        "String",
    ),
    (
        "GlyphOrientationVertical",
        "glyph-orientation-vertical",
        "String",
    ),
    ("GlyphRef", "glyphRef", "String"),
    ("GradientTransform", "gradientTransform", "String"),
    ("GradientUnits", "gradientUnits", "String"),
    ("Hanging", "hanging", "String"),
    ("Height", "height", "Length"),
    ("HorizAdvX", "horiz-adv-x", "String"),
    ("HorizOriginX", "horiz-origin-x", "String"),
    ("HorizOriginY", "horiz-origin-y", "String"),
    ("Href", "href", "String"),
    ("Id", "id", "String"),
    ("Ideographic", "ideographic", "String"),
    ("ImageRendering", "image-rendering", "String"),
    ("In", "in", "String"),
    ("In2", "in2", "String"),
    ("Intercept", "intercept", "String"),
    ("K", "k", "String"),
    ("K1", "k1", "String"),
    ("K2", "k2", "String"),
    ("K3", "k3", "String"),
    ("K4", "k4", "String"),
    ("KernelMatrix", "kernelMatrix", "String"),
    ("KernelUnitLength", "kernelUnitLength", "String"),
    ("Kerning", "kerning", "String"),
    ("KeyPoints", "keyPoints", "String"),
    ("KeySplines", "keySplines", "String"),
    ("KeyTimes", "keyTimes", "String"),
    ("Lang", "lang", "String"),
    ("LengthAdjust", "lengthAdjust", "String"),
    ("LetterSpacing", "letter-spacing", "String"),
    ("LightingColor", "lighting-color", "String"),
    ("LimitingConeAngle", "limitingConeAngle", "String"),
    ("LineHeight", "line-height", "String"),
    ("Local", "local", "String"),
    ("Marker", "marker", "String"),
    ("MarkerEnd", "marker-end", "String"),
    ("MarkerMid", "marker-mid", "String"),
    ("MarkerStart", "marker-start", "String"),
    ("MarkerHeight", "markerHeight", "String"),
    ("MarkerUnits", "markerUnits", "String"),
    ("MarkerWidth", "markerWidth", "String"),
    ("Mask", "mask", "String"),
    ("MaskContentUnits", "maskContentUnits", "String"),
    ("MaskUnits", "maskUnits", "String"),
    ("Mathematical", "mathematical", "String"),
    ("Max", "max", "String"),
    ("Media", "media", "String"),
    ("Method", "method", "String"),
    ("Min", "min", "String"),
    ("Mode", "mode", "String"),
    ("Name", "name", "String"),
    ("NumOctaves", "numOctaves", "String"),
    ("Offset", "offset", "String"),
    ("Onabort", "onabort", "String"),
    ("Onactivate", "onactivate", "String"),
    ("Onbegin", "onbegin", "String"),
    ("Onclick", "onclick", "String"),
    ("Onend", "onend", "String"),
    ("Onerror", "onerror", "String"),
    ("Onfocusin", "onfocusin", "String"),
    ("Onfocusout", "onfocusout", "String"),
    ("Onload", "onload", "String"),
    ("Onmousedown", "onmousedown", "String"),
    ("Onmousemove", "onmousemove", "String"),
    ("Onmouseout", "onmouseout", "String"),
    ("Onmouseover", "onmouseover", "String"),
    ("Onmouseup", "onmouseup", "String"),
    ("Onrepeat", "onrepeat", "String"),
    ("Onresize", "onresize", "String"),
    ("Onscroll", "onscroll", "String"),
    ("Onunload", "onunload", "String"),
    ("Onzoom", "onzoom", "String"),
    ("Opacity", "opacity", "String"),
    ("Operator", "operator", "String"),
    ("Order", "order", "String"),
    ("Orient", "orient", "String"),
    ("Orientation", "orientation", "String"),
    ("Origin", "origin", "String"),
    ("Overflow", "overflow", "String"),
    ("OverlinePosition", "overline-position", "String"),
    ("OverlineThickness", "overline-thickness", "String"),
    ("Panose1", "panose-1", "String"),
    ("Path", "path", "String"),
    ("PathLength", "pathLength", "String"),
    ("PatternContentUnits", "patternContentUnits", "String"),
    ("PatternTransform", "patternTransform", "String"),
    ("PatternUnits", "patternUnits", "String"),
    ("PointerEvents", "pointer-events", "String"),
    ("Points", "points", "String"),
    ("PointsAtX", "pointsAtX", "String"),
    ("PointsAtY", "pointsAtY", "String"),
    ("PointsAtZ", "pointsAtZ", "String"),
    ("PreserveAlpha", "preserveAlpha", "String"),
    ("PreserveAspectRatio", "preserveAspectRatio", "String"),
    ("PrimitiveUnits", "primitiveUnits", "String"),
    ("R", "r", "String"),
    ("Radius", "radius", "String"),
    ("RefX", "refX", "String"),
    ("RefY", "refY", "String"),
    ("RenderingIntent", "rendering-intent", "String"),
    ("RepeatCount", "repeatCount", "String"),
    ("RepeatDur", "repeatDur", "String"),
    ("RequiredExtensions", "requiredExtensions", "String"),
    ("RequiredFeatures", "requiredFeatures", "String"),
    ("Restart", "restart", "String"),
    ("Result", "result", "String"),
    ("Role", "role", "String"),
    ("Rotate", "rotate", "String"),
    ("Rx", "rx", "String"),
    ("Ry", "ry", "String"),
    ("Scale", "scale", "String"),
    ("Seed", "seed", "String"),
    ("ShapeRendering", "shape-rendering", "String"),
    ("Show", "show", "String"),
    ("Slope", "slope", "String"),
    ("Space", "space", "String"),
    ("Spacing", "spacing", "String"),
    ("SpecularConstant", "specularConstant", "String"),
    ("SpecularExponent", "specularExponent", "String"),
    ("SpreadMethod", "spreadMethod", "String"),
    ("StartOffset", "startOffset", "String"),
    ("StdDeviation", "stdDeviation", "String"),
    ("Stemh", "stemh", "String"),
    ("Stemv", "stemv", "String"),
    ("StitchTiles", "stitchTiles", "String"),
    ("StopColor", "stop-color", "Color"),
    ("StopOpacity", "stop-opacity", "String"),
    ("StrikethroughPosition", "strikethrough-position", "String"),
    (
        "StrikethroughThickness",
        "strikethrough-thickness",
        "String",
    ),
    ("String", "string", "String"),
    ("Stroke", "stroke", "String"),
    ("StrokeDasharray", "stroke-dasharray", "String"),
    ("StrokeDashoffset", "stroke-dashoffset", "String"),
    ("StrokeLinecap", "stroke-linecap", "String"),
    ("StrokeLinejoin", "stroke-linejoin", "String"),
    ("StrokeMiterlimit", "stroke-miterlimit", "String"),
    ("StrokeOpacity", "stroke-opacity", "String"),
    ("StrokeWidth", "stroke-width", "String"),
    ("Style", "style", "String"),
    ("SurfaceScale", "surfaceScale", "String"),
    ("SystemLanguage", "systemLanguage", "String"),
    ("TableValues", "tableValues", "String"),
    ("Target", "target", "String"),
    ("TargetX", "targetX", "String"),
    ("TargetY", "targetY", "String"),
    ("TextAnchor", "text-anchor", "String"),
    ("TextDecoration", "text-decoration", "String"),
    ("TextRendering", "text-rendering", "String"),
    ("TextLength", "textLength", "String"),
    ("Title", "title", "String"),
    ("To", "to", "String"),
    ("Transform", "transform", "String"),
    ("Type", "type", "String"),
    ("U1", "u1", "String"),
    ("U2", "u2", "String"),
    ("UnderlinePosition", "underline-position", "String"),
    ("UnderlineThickness", "underline-thickness", "String"),
    ("Unicode", "unicode", "String"),
    ("UnicodeBidi", "unicode-bidi", "String"),
    ("UnicodeRange", "unicode-range", "String"),
    ("UnitsPerEm", "units-per-em", "String"),
    ("VAlphabetic", "v-alphabetic", "String"),
    ("VHanging", "v-hanging", "String"),
    ("VIdeographic", "v-ideographic", "String"),
    ("VMathematical", "v-mathematical", "String"),
    ("Values", "values", "String"),
    ("Version", "version", "String"),
    ("VertAdvY", "vert-adv-y", "String"),
    ("VertOriginX", "vert-origin-x", "String"),
    ("VertOriginY", "vert-origin-y", "String"),
    ("ViewBox", "viewBox", "String"),
    ("ViewTarget", "viewTarget", "String"),
    ("Visibility", "visibility", "String"),
    ("Width", "width", "Length"),
    ("Widths", "widths", "String"),
    ("WordSpacing", "word-spacing", "String"),
    ("WritingMode", "writing-mode", "String"),
    ("X", "x", "Length"),
    ("XHeight", "x-height", "String"),
    ("X1", "x1", "String"),
    ("X2", "x2", "String"),
    ("XChannelSelector", "xChannelSelector", "String"),
    ("Xlink", "xlink", "String"),
    ("Xmlns", "xmlns", "String"),
    ("Y", "y", "Length"),
    ("Y1", "y1", "String"),
    ("Y2", "y2", "String"),
    ("YChannelSelector", "yChannelSelector", "String"),
    ("Z", "z", "String"),
    ("ZoomAndPan", "zoomAndPan", "String"),
];

fn main() -> Result<(), std::fmt::Error> {
    let dest_path = Path::new("generated/attribute.rs");

    let mut attrs = Vec::from(ATTRIBUTES);
    attrs.sort_by(|a, b| a.1.cmp(&b.1));

    let mut value_tys = HashSet::new();

    let mut buf = String::default();

    writeln!(buf, "// THIS FILE IS AUTOGENERATED.\n// Any changes to this file will be overwritten.\n// See build.rs for details.\n")?;

    writeln!(
        buf,
        "const ATTRIBUTE_VALIDATORS: &[(&str, fn(&Value) -> bool)] = &["
    )?;
    for (name, id, ty) in &attrs {
        writeln!(buf, "    ({:?}, id::{}::validate),", id, name)?;
        value_tys.insert(ty);
    }
    writeln!(buf, "];\n")?;

    writeln!(buf, "pub mod id {{")?;
    writeln!(buf, "    use super::AttributeDescriptor;")?;
    for (name, id, ty) in &attrs {
        writeln!(buf, "    attr_desc!({}, {:?}, super::{});", name, id, ty)?;
    }
    writeln!(buf, "}}\n")?;

    for value_ty in &value_tys {
        writeln!(buf, "value_desc!({});", value_ty)?;
    }

    fs::write(&dest_path, &buf).unwrap();
    println!("cargo:rerun-if-changed=build.rs");
    Ok(())
}
